#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup-mac — one-time bootstrap for a local copy of the Electrical CRM on macOS.
# Checks prerequisites, writes backend/.env with freshly generated secrets, and
# installs dependencies. Safe to re-run: an existing .env is never overwritten.
# Day-to-day running of the app is ./crm.sh — see SETUP-MAC.md.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$REPO/backend/.env"
NODE_MIN=20

ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
bad()  { printf '  \033[31m✗\033[0m %s\n' "$1"; }
step() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }

fail() { bad "$1"; echo; echo "Setup stopped. Fix the above and re-run: ./setup-mac.sh"; exit 1; }

# ── 1. Prerequisites ────────────────────────────────────────────────────────
step "Checking prerequisites"

[ "$(uname -s)" = "Darwin" ] || warn "This script is written for macOS; continuing anyway."

if command -v brew >/dev/null 2>&1; then
  ok "Homebrew $(brew --version | head -1 | awk '{print $2}')"
else
  bad "Homebrew not found."
  echo "     Install it, then re-run this script:"
  echo '     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  exit 1
fi

if command -v node >/dev/null 2>&1; then
  NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
  if [ "$NODE_MAJOR" -ge "$NODE_MIN" ]; then
    ok "Node $(node -v)"
  else
    fail "Node $(node -v) is too old — this project needs Node ${NODE_MIN}+. Upgrade with: brew upgrade node"
  fi
else
  bad "Node not found. Install it, then re-run this script:"
  echo "     brew install node"
  exit 1
fi

if command -v docker >/dev/null 2>&1; then
  if docker info >/dev/null 2>&1; then
    ok "Docker is running"
  else
    fail "Docker is installed but not running. Open Docker Desktop, wait for the whale icon to settle, then re-run."
  fi
else
  bad "Docker not found. Install Docker Desktop, open it once, then re-run this script:"
  echo "     brew install --cask docker"
  exit 1
fi

# ── 2. backend/.env ─────────────────────────────────────────────────────────
step "Configuring backend/.env"

if [ -f "$ENV_FILE" ]; then
  ok "backend/.env already exists — leaving it untouched"
else
  # Hex output: alphanumeric, so it survives being typed at a login prompt and
  # pasted into shells. Avoids a `tr | head` pipeline, which raises SIGPIPE and
  # would trip `set -o pipefail` above. Argument is the number of random bytes.
  gen() { openssl rand -hex "$1"; }

  ADMIN_EMAIL=""
  if [ -t 0 ]; then
    printf '  Login email for your local admin account [admin@local.test]: '
    read -r ADMIN_EMAIL || true
  fi
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@local.test}"
  ADMIN_PASSWORD="$(gen 10)"   # 20 hex chars

  cat > "$ENV_FILE" <<EOF
# Local development settings for the Electrical CRM.
# Generated by setup-mac.sh — this file is gitignored and stays on this Mac.
# Values here are for the local sandbox only; production is configured on Render.

# ── Database (the Postgres container from docker-compose.yml) ────────────────
DB_HOST=localhost
DB_PORT=5432
DB_NAME=electrical_crm
DB_USER=postgres
DB_PASS=postgres

# ── Server ──────────────────────────────────────────────────────────────────
PORT=3001

# ── Auth ────────────────────────────────────────────────────────────────────
JWT_SECRET=$(gen 32)

# ── Initial account bootstrap ───────────────────────────────────────────────
# Used ONCE, only while the users table is empty, to create the first owner
# login (backend/src/migrate.ts). This is your local login — see SETUP-MAC.md.
SEED_ADMIN_EMAIL=$ADMIN_EMAIL
SEED_ADMIN_PASSWORD=$ADMIN_PASSWORD
SEED_ADMIN_NAME=Administrator

# ── Optional integrations ───────────────────────────────────────────────────
# All of these are OFF locally and the app degrades gracefully without them.
# Fill one in only if you want to exercise that feature on this machine; see
# .env.example for what each one is.
# ANTHROPIC_API_KEY=
# CLOUDINARY_CLOUD_NAME=
# CLOUDINARY_API_KEY=
# CLOUDINARY_API_SECRET=
# GOOGLE_SERVICE_ACCOUNT_JSON=
# AUTOMATION_API_KEY=
EOF

  chmod 600 "$ENV_FILE"
  ok "Wrote backend/.env with a freshly generated JWT secret"
  ok "Local login: $ADMIN_EMAIL / $ADMIN_PASSWORD"
fi

# ── 3. Dependencies ─────────────────────────────────────────────────────────
step "Installing dependencies (this takes a few minutes the first time)"

( cd "$REPO/backend"  && npm install --no-fund --no-audit ) && ok "backend"
( cd "$REPO/frontend" && npm install --no-fund --no-audit ) && ok "frontend"

chmod +x "$REPO/crm.sh"

# ── Done ────────────────────────────────────────────────────────────────────
LOGIN_EMAIL="$(grep -E '^SEED_ADMIN_EMAIL=' "$ENV_FILE" | cut -d= -f2-)"
LOGIN_PASS="$(grep -E '^SEED_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"

cat <<EOF

──────────────────────────────────────────────────────────
 Setup complete.

   Start the app:   ./crm.sh
   Then open:       http://localhost:3000

   Login:  ${LOGIN_EMAIL}
   Pass:   ${LOGIN_PASS}

   Sample data:     ./crm.sh seed
   Stop:            ./crm.sh down
   Full reference:  SETUP-MAC.md
──────────────────────────────────────────────────────────
EOF
