// Phase 3 Task 7 — job_number is auto-generated by composeBidData/jobNumber
// on first proposal generation (see bidStandardGeneration.test.ts's "generates
// and persists a job number on first use") but is also editable directly,
// same pattern as every other bid field (bids.ts's PATCH /:id).
import { describe, it, expect, beforeAll } from 'vitest';
import request from 'supertest';
import { app } from '../index';
import { dbAvailable, makeUser, auth } from './harness';

let ok = false;
beforeAll(async () => { ok = await dbAvailable(); }, 30_000);

describe('bid job_number editing', () => {
  it('is null on a freshly created bid', async (ctx) => {
    if (!ok) return ctx.skip();
    const u = await makeUser('owner');
    const res = await request(app).post('/api/bids').set(auth(u.token))
      .send({ name: `JobNo ${Date.now()}`, gc: 'Test GC' }).expect(200);
    expect(res.body.job_number).toBeNull();
  });

  it('PATCH /:id sets job_number', async (ctx) => {
    if (!ok) return ctx.skip();
    const u = await makeUser('owner');
    const bid = await request(app).post('/api/bids').set(auth(u.token))
      .send({ name: `JobNoEdit ${Date.now()}`, gc: 'Test GC' }).expect(200);
    const res = await request(app).patch(`/api/bids/${bid.body.id}`).set(auth(u.token))
      .send({ job_number: 'JS.09022026' }).expect(200);
    expect(res.body.bid.job_number).toBe('JS.09022026');
  });

  it('PATCH /:id clears job_number with an empty string', async (ctx) => {
    if (!ok) return ctx.skip();
    const u = await makeUser('owner');
    const bid = await request(app).post('/api/bids').set(auth(u.token))
      .send({ name: `JobNoClear ${Date.now()}`, gc: 'Test GC' }).expect(200);
    await request(app).patch(`/api/bids/${bid.body.id}`).set(auth(u.token))
      .send({ job_number: 'JS.09022026' }).expect(200);
    const res = await request(app).patch(`/api/bids/${bid.body.id}`).set(auth(u.token))
      .send({ job_number: '' }).expect(200);
    expect(res.body.bid.job_number).toBeNull();
  });
});
