// @vitest-environment jsdom
// DOMPurify needs a real TreeWalker/DOM implementation to sanitize correctly;
// happy-dom (used elsewhere in this repo) has known gaps there, jsdom is
// DOMPurify's own documented Node test environment.
import { describe, it, expect } from 'vitest';
import * as XLSX from 'xlsx';
import { previewKind, sanitizeDocHtml, fixSheetRange } from './filePreview';

describe('previewKind', () => {
  it('pdf and images are inline', () => {
    expect(previewKind('plans.pdf', 'application/pdf')).toBe('inline');
    expect(previewKind('photo.jpg', 'image/jpeg')).toBe('inline');
    expect(previewKind('scan.PDF', null)).toBe('inline');
  });
  it('legacy docs with null file_type fall back to the image extension', () => {
    expect(previewKind('photo.jpg', null)).toBe('inline');
    expect(previewKind('photo.jpeg', null)).toBe('inline');
    expect(previewKind('logo.png', null)).toBe('inline');
    expect(previewKind('animation.gif', null)).toBe('inline');
    expect(previewKind('banner.webp', null)).toBe('inline');
  });
  it('spreadsheets are sheet', () => {
    expect(previewKind('takeoff.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')).toBe('sheet');
    expect(previewKind('old.xls', null)).toBe('sheet');
    expect(previewKind('export.csv', 'text/csv')).toBe('sheet');
  });
  it('docx is doc', () => {
    expect(previewKind('proposal.docx', null)).toBe('doc');
  });
  it('unknown is none', () => {
    expect(previewKind('archive.zip', 'application/zip')).toBe('none');
  });
});

describe('sanitizeDocHtml', () => {
  it('neutralizes a javascript: hyperlink', () => {
    const out = sanitizeDocHtml('<a href="javascript:alert(1)">click me</a>');
    expect(out).not.toContain('javascript:');
    expect(out).toContain('click me');
  });

  it('strips onclick and other event-handler attributes', () => {
    const out = sanitizeDocHtml('<p onclick="alert(1)">hi</p>');
    expect(out).not.toContain('onclick');
    expect(out).not.toContain('alert(1)');
    expect(out).toContain('hi');
  });

  it('preserves a plain https link', () => {
    const out = sanitizeDocHtml('<a href="https://example.com">site</a>');
    expect(out).toContain('href="https://example.com"');
    expect(out).toContain('site');
  });

  it('strips a protocol-relative href (schemeless off-site redirect)', () => {
    const out = sanitizeDocHtml('<a href="//evil.com">click me</a>');
    expect(out).not.toContain('href=');
    expect(out).toContain('click me');
  });

  it('preserves a root-relative href', () => {
    const out = sanitizeDocHtml('<a href="/files/report.pdf">report</a>');
    expect(out).toContain('href="/files/report.pdf"');
    expect(out).toContain('report');
  });

  it('removes script tags entirely, including their contents', () => {
    const out = sanitizeDocHtml('<p>before</p><script>alert(1)</script><p>after</p>');
    expect(out).not.toContain('<script');
    expect(out).not.toContain('alert(1)');
    expect(out).toContain('before');
    expect(out).toContain('after');
  });

  it('drops disallowed elements like iframe while keeping safe content', () => {
    const out = sanitizeDocHtml('<p>text</p><iframe src="javascript:alert(1)"></iframe>');
    expect(out).not.toContain('<iframe');
    expect(out).toContain('text');
  });
});

describe('fixSheetRange', () => {
  // Takeoff workbooks generated by some estimating software carry a <dimension>
  // element that undersells the sheet's real extent (e.g. A1:A3 when data
  // actually spans through column D). SheetJS trusts that element for ws['!ref'],
  // so sheet_to_json on the untouched worksheet drops every cell outside it —
  // the preview modal ends up showing item numbers with every description/
  // unit/qty column blank. fixSheetRange recomputes '!ref' from the worksheet's
  // actual cell keys so the full row survives.
  it('recomputes a lying !ref so sheet_to_json returns the full row, not just column A', () => {
    const ws = XLSX.utils.aoa_to_sheet([
      ['1.1', 'Panelboard A', 'EA', 1],
      ['1.2', 'Panelboard B', 'EA', 2],
      ['1.3', 'Panelboard C', 'EA', 3],
    ]);
    // Simulate the lying dimension: real data is A1:D3, claimed range is A1:A3.
    ws['!ref'] = 'A1:A3';

    // RED (without the fix applied): sheet_to_json on the untouched worksheet
    // only sees column A, because it trusts the lying !ref.
    const lyingRows = XLSX.utils.sheet_to_json<string[]>(ws, { header: 1 });
    expect(lyingRows[0]).toEqual(['1.1']);

    // GREEN: fixSheetRange recomputes the range from the actual cell keys,
    // and sheet_to_json now returns every column.
    const fixed = fixSheetRange(ws);
    const rows = XLSX.utils.sheet_to_json<string[]>(fixed, { header: 1 });
    expect(rows[0]).toEqual(['1.1', 'Panelboard A', 'EA', 1]);
    expect(rows[1]).toEqual(['1.2', 'Panelboard B', 'EA', 2]);
    expect(rows[2]).toEqual(['1.3', 'Panelboard C', 'EA', 3]);
    expect(fixed['!ref']).toBe('A1:D3');
  });

  it('is a no-op on a worksheet with no cell keys', () => {
    const ws: XLSX.WorkSheet = { '!ref': 'A1:A1' };
    fixSheetRange(ws);
    expect(ws['!ref']).toBe('A1:A1');
  });
});
