// Takeoff accuracy — a small, dependency-free VECTOR plan-set PDF with drawn
// fixture symbols at known PDF coordinates, for real-pdftoppm tests of the
// counting renderer (tile geometry, CropBox, non-zero origin, /Rotate) and
// the pipeline integration test. The generated bytes are committed as
// kissimmee-mini.pdf (see ai/countRender.test.ts's byte-equality check), so a
// reviewer can open the exact file the tests run on.
//
// Symbols are filled 14 pt squares ("re f"); each carries its type tag as
// text 40 pt above-right so a centroid search around the square never picks
// up the tag. Coordinates are absolute PDF user space (the MediaBox origin
// may be non-zero, exactly like a CAD export).

export interface SymbolSpec { type: string; x: number; y: number }
export interface TextSpec { x: number; y: number; size: number; text: string }

export interface SymbolPage {
  mediaBox: [number, number, number, number];
  cropBox?: [number, number, number, number];
  rotate?: number;
  symbols: SymbolSpec[];
  texts: TextSpec[];
}

export const SYMBOL_SIZE_PT = 14;

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function contentStream(p: SymbolPage): string {
  const ops: string[] = ['0 g'];
  const h = SYMBOL_SIZE_PT / 2;
  for (const s of p.symbols) {
    ops.push(`${(s.x - h).toFixed(2)} ${(s.y - h).toFixed(2)} ${SYMBOL_SIZE_PT} ${SYMBOL_SIZE_PT} re f`);
  }
  for (const s of p.symbols) {
    ops.push(`BT /F1 9 Tf ${(s.x + 28).toFixed(2)} ${(s.y + 28).toFixed(2)} Td (${esc(s.type)}) Tj ET`);
  }
  for (const t of p.texts) {
    ops.push(`BT /F1 ${t.size} Tf ${t.x.toFixed(2)} ${t.y.toFixed(2)} Td (${esc(t.text)}) Tj ET`);
  }
  return ops.join('\n');
}

export function buildSymbolPdf(pages: SymbolPage[]): Buffer {
  // Object numbering: 1 catalog, 2 pages, 3 font, then (page, content) pairs.
  const objects: string[] = [];
  const pageIds = pages.map((_, i) => 4 + i * 2);
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[2] = `<< /Type /Pages /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
  pages.forEach((p, i) => {
    const pageId = pageIds[i];
    const contentId = pageId + 1;
    const stream = contentStream(p);
    const box = (b: number[]) => `[${b.join(' ')}]`;
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox ${box(p.mediaBox)}${p.cropBox ? ` /CropBox ${box(p.cropBox)}` : ''}${p.rotate ? ` /Rotate ${p.rotate}` : ''} /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, 'latin1')} >>\nstream\n${stream}\nendstream`;
  });

  let out = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (let id = 1; id < objects.length; id++) {
    offsets[id] = Buffer.byteLength(out, 'latin1');
    out += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xrefAt = Buffer.byteLength(out, 'latin1');
  out += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id++) out += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
}

// ── The committed "Kissimmee-mini" set ───────────────────────────────────────
// 24" x 18" sheets (1728 x 1296 pt). Title block text sits in the right 10%.
//   p1  E-0.1 FIXTURE SCHEDULE  (schedule sheet — never counted)
//   p2  E-3 LIGHTING PLAN       MediaBox origin (100,200), CropBox inset 36 pt,
//                               /Rotate 90 — the hard geometry case
//   p3  E-1 ELECTRICAL SITE PLAN  poles S1 x2, S2 x1 (rotation 0)
//   p4  PH0.1 PHOTOMETRIC SITE PLAN  the same poles again (never counted)
const W = 1728;
const H = 1296;

function titleBlock(x0: number, y0: number, w: number, sheetNo: string, title: string): TextSpec[] {
  // Rotation 0 pages: title block in the right 10% of the page.
  const x = x0 + w * 0.92;
  return [
    { x, y: y0 + 120, size: 16, text: sheetNo },
    { x, y: y0 + 90, size: 8, text: title },
  ];
}

// p2 geometry: unrotated MediaBox [100 200 1396 1928] (1296 wide x 1728 tall)
// shown with /Rotate 90 -> displayed 1728 x 1296 landscape. A symbol's
// displayed position is (relY, relX), so the title block (displayed right
// strip, dx > 0.9 * displayed width) sits at relY > ~1555 — high y.
export const MINI_P2_MEDIA: [number, number, number, number] = [100, 200, 1396, 1928];
export const MINI_P2_CROP: [number, number, number, number] = [136, 236, 1360, 1892];

export const MINI_P2_SYMBOLS: SymbolSpec[] = [
  // Type A x6 (interior), type B x3, type D wall packs x3 (building exterior).
  { type: 'A', x: 300, y: 400 }, { type: 'A', x: 420, y: 400 }, { type: 'A', x: 540, y: 400 },
  { type: 'A', x: 300, y: 700 }, { type: 'A', x: 420, y: 700 },
  { type: 'B', x: 700, y: 900 }, { type: 'B', x: 900, y: 900 },
  { type: 'D', x: 180, y: 300 }, { type: 'D', x: 1250, y: 1300 }, { type: 'D', x: 180, y: 1400 },
  // In the tile overlap bands (so a counter that reports a symbol in every
  // tile showing it reports these 2-4 times): a type A at the R1C1/R1C2/
  // R2C1/R2C2 four-tile corner (displayed ~7.0", 5.8") and a type B on the
  // R1C2/R1C3 seam (displayed ~13.6", 2.0").
  { type: 'A', x: 554, y: 740 },
  { type: 'B', x: 280, y: 1215 },
];

export const MINI_P3_SYMBOLS: SymbolSpec[] = [
  { type: 'S1', x: 250, y: 250 }, { type: 'S1', x: 900, y: 1100 }, { type: 'S2', x: 1300, y: 300 },
];

export function kissimmeeMiniPages(): SymbolPage[] {
  return [
    {
      mediaBox: [0, 0, W, H],
      symbols: [],
      texts: [
        { x: 72, y: 1200, size: 14, text: 'LUMINAIRE SCHEDULE' },
        { x: 72, y: 1170, size: 10, text: 'A  4 FT LED LINEAR WRAPAROUND  32W' },
        { x: 72, y: 1150, size: 10, text: 'B  8 FT LED LINEAR WRAPAROUND  64W' },
        { x: 72, y: 1130, size: 10, text: 'D  LED WALL PACK  40W' },
        { x: 72, y: 1110, size: 10, text: 'S1  LED AREA LIGHT SINGLE HEAD 25 FT POLE  150W' },
        { x: 72, y: 1090, size: 10, text: 'S2  LED AREA LIGHT TWIN HEAD 25 FT POLE  300W' },
        ...titleBlock(0, 0, W, 'E-0.1', 'FIXTURE SCHEDULE'),
      ],
    },
    {
      mediaBox: MINI_P2_MEDIA,
      cropBox: MINI_P2_CROP,
      rotate: 90,
      symbols: MINI_P2_SYMBOLS,
      // Title block for a /Rotate 90 page: high relY (displayed right strip).
      texts: [
        { x: 300, y: 1800, size: 16, text: 'E-3' },
        { x: 300, y: 1780, size: 8, text: 'LIGHTING PLAN' },
      ],
    },
    {
      mediaBox: [0, 0, W, H],
      symbols: MINI_P3_SYMBOLS,
      texts: titleBlock(0, 0, W, 'E-1', 'ELECTRICAL SITE PLAN'),
    },
    {
      mediaBox: [0, 0, W, H],
      symbols: MINI_P3_SYMBOLS,
      texts: titleBlock(0, 0, W, 'PH0.1', 'PHOTOMETRIC SITE PLAN'),
    },
  ];
}

export function buildKissimmeeMiniPdf(): Buffer {
  return buildSymbolPdf(kissimmeeMiniPages());
}
