ALTER TABLE takeoff_results
  ADD COLUMN IF NOT EXISTS usage_agent1 JSONB,
  ADD COLUMN IF NOT EXISTS usage_agent2 JSONB,
  ADD COLUMN IF NOT EXISTS usage_agent3 JSONB,
  ADD COLUMN IF NOT EXISTS model_agent1 TEXT,
  ADD COLUMN IF NOT EXISTS model_agent2 TEXT,
  ADD COLUMN IF NOT EXISTS model_agent3 TEXT;
