ALTER TABLE takeoff_results
  ADD COLUMN IF NOT EXISTS agent4_output TEXT,
  ADD COLUMN IF NOT EXISTS agent4_price NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS agent4_notes TEXT,
  ADD COLUMN IF NOT EXISTS agent4_model TEXT,
  ADD COLUMN IF NOT EXISTS usage_agent4 JSONB;
