-- Historical one-time cleanup (applied 2026-0x-xx). Neutralized 2026-09-04:
-- the TRUNCATE was removed so this file can never wipe data on a database whose
-- schema_migrations table is missing. See git history for the original.
