import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, ImageRun, ShadingType,
  convertInchesToTwip, NumberFormat,
} from 'docx';
import * as fs from 'fs';
import * as path from 'path';

export interface ProposalJSON {
  date?: string;
  gcName?: string;
  gcContact?: string;
  gcEmail?: string;
  projectName?: string;
  projectAddress?: string;
  jobNumber?: string;
  drawingDate?: string;
  sheets?: string[];
  openingStatement?: string;
  scopeOfWork?: {
    standard6Bullets?: string[];
    A_ServiceDistribution?: string[];
    B_BranchPower?: string[];
    C_LightingControls?: string[];
    D_SiteLightingUnderground?: string[];
    E_LowVoltage?: string[];
    F_Coordination?: string[];
  };
  exclusions?: string[];
  allowances?: Array<{ item: string; footage: number; unit: string; notes: string }>;
  takeoff?: Array<{ category: string; item: string; description: string; unit: string; qty: number; sourceNotes: string }>;
  terms?: string[];
  totalPrice?: string;
  rfisToResolve?: string[];
}

const NAVY = '1F3864';
const WHITE = 'FFFFFF';
const GRAY = 'F2F2F2';
const FONT = 'Arial';
const SM  = 18;  // 9pt in half-points
const MD  = 20;  // 10pt
const LG  = 24;  // 12pt
const XL  = 36;  // 18pt

// Standard APT opening statement — fixed boilerplate, not generated by Agent 4.
const aptOpening = (project: string) =>
  `Please accept this proposal to complete the electrical work for ${project} you have out for bid.`;

// Optional authoritative project fields sourced from the bid record. These take
// precedence over Agent 4's generated values where provided.
export interface BidMeta {
  projectName?: string;
  projectAddress?: string;
  gcName?: string;
  gcContact?: string;
}

// Format any date-ish input as "Month DD, YYYY" (e.g. "June 8, 2026"). Falls
// back to today when the value is missing or unparseable — never emits ISO.
function formatDate(v: unknown): string {
  const today = new Date();
  const fmt = (d: Date) =>
    d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const s = toStr(v).trim();
  if (!s) return fmt(today);
  // Accept ISO (2026-06-08) and other Date-parseable strings.
  const parsed = new Date(/^\d{4}-\d{2}-\d{2}$/.test(s) ? `${s}T00:00:00` : s);
  return isNaN(parsed.getTime()) ? fmt(today) : fmt(parsed);
}

// Claude occasionally returns array items as objects instead of strings.
// Flatten any such value to a readable string so the docx builder never crashes.
function toStr(v: unknown): string {
  if (typeof v === 'string') return v;
  if (v && typeof v === 'object') {
    const o = v as Record<string, unknown>;
    return [o.item, o.text, o.description, o.question, o.risks, o.risk, o.note]
      .filter(Boolean).map(String).join(' — ') || JSON.stringify(v);
  }
  return String(v ?? '');
}

type ImgType = 'jpg' | 'png' | 'gif';

function loadAsset(assetsDir: string, names: string[]): { buf: Buffer; type: ImgType } | null {
  for (const name of names) {
    const p = path.join(assetsDir, name);
    if (fs.existsSync(p)) {
      const buf = fs.readFileSync(p);
      const ext = name.split('.').pop()?.toLowerCase();
      const type: ImgType = ext === 'png' ? 'png' : ext === 'gif' ? 'gif' : 'jpg';
      return { buf, type };
    }
  }
  return null;
}

const NO_BORDER = {
  top:     { style: BorderStyle.NONE, size: 0, color: 'auto' },
  bottom:  { style: BorderStyle.NONE, size: 0, color: 'auto' },
  left:    { style: BorderStyle.NONE, size: 0, color: 'auto' },
  right:   { style: BorderStyle.NONE, size: 0, color: 'auto' },
  insideH: { style: BorderStyle.NONE, size: 0, color: 'auto' },
  insideV: { style: BorderStyle.NONE, size: 0, color: 'auto' },
} as const;

const CELL_NO_BORDER = {
  top:    { style: BorderStyle.NONE, size: 0, color: 'auto' },
  bottom: { style: BorderStyle.NONE, size: 0, color: 'auto' },
  left:   { style: BorderStyle.NONE, size: 0, color: 'auto' },
  right:  { style: BorderStyle.NONE, size: 0, color: 'auto' },
} as const;

function navyHeader(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, color: WHITE, size: LG, font: FONT })],
    shading: { type: ShadingType.SOLID, fill: NAVY, color: NAVY },
    alignment: AlignmentType.CENTER,
    spacing: { before: 280, after: 120 },
  });
}

// Scope A–F subsection header — same navy band, slightly smaller text.
function subHeader(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, color: WHITE, size: MD, font: FONT })],
    shading: { type: ShadingType.SOLID, fill: NAVY, color: NAVY },
    alignment: AlignmentType.CENTER,
    spacing: { before: 180, after: 80 },
  });
}

function bodyPara(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: MD, font: FONT })],
    spacing: { before: 40, after: 60 },
  });
}

function blank(): Paragraph {
  return new Paragraph({ children: [new TextRun('')], spacing: { before: 0, after: 100 } });
}

function numberedItem(text: string): Paragraph {
  return new Paragraph({
    numbering: { reference: 'numbered-list', level: 0 },
    children: [new TextRun({ text, size: MD, font: FONT })],
    spacing: { before: 60, after: 60 },
  });
}

function bulletItem(text: string): Paragraph {
  return new Paragraph({
    numbering: { reference: 'bullet-list', level: 0 },
    children: [new TextRun({ text, size: MD, font: FONT })],
    spacing: { before: 60, after: 60 },
  });
}

function hdrCell(text: string, widthPct?: number): TableCell {
  return new TableCell({
    ...(widthPct ? { width: { size: widthPct, type: WidthType.PERCENTAGE } } : {}),
    shading: { type: ShadingType.SOLID, fill: NAVY, color: NAVY },
    children: [new Paragraph({
      children: [new TextRun({ text, bold: true, color: WHITE, size: SM, font: FONT })],
      spacing: { before: 60, after: 60 },
      indent: { left: 80, right: 80 },
    })],
  });
}

function dataCell(text: string, stripe: boolean, widthPct?: number, fontSize = SM): TableCell {
  return new TableCell({
    ...(widthPct ? { width: { size: widthPct, type: WidthType.PERCENTAGE } } : {}),
    ...(stripe ? { shading: { type: ShadingType.SOLID, fill: GRAY, color: GRAY } } : {}),
    children: [new Paragraph({
      children: [new TextRun({ text, size: fontSize, font: FONT })],
      spacing: { before: 40, after: 40 },
      indent: { left: 80, right: 80 },
    })],
  });
}


export async function buildProposalDocx(data: ProposalJSON, bidMeta: BidMeta = {}): Promise<Buffer> {
  const ASSETS_DIR = path.resolve(__dirname, '../../assets');
  const logo = loadAsset(ASSETS_DIR, ['logo.png', 'logo.jpg', 'logo.jpeg']);
  const sig  = loadAsset(ASSETS_DIR, ['signature.png', 'signature.jpg', 'sig.png', 'sig.jpg']);

  // Coerce every scalar field so TextRun never receives a non-string value.
  // Bid-record values (bidMeta) are authoritative and take precedence over Agent 4.
  const gcName        = toStr(bidMeta.gcName)        || toStr(data.gcName) || '—';
  const gcContact     = toStr(bidMeta.gcContact)     || toStr(data.gcContact);
  const gcEmail       = toStr(data.gcEmail);
  const date          = formatDate(data.date);
  const projectName   = toStr(bidMeta.projectName)   || toStr(data.projectName) || '—';
  const projectAddr   = toStr(bidMeta.projectAddress) || toStr(data.projectAddress);
  const jobNumber     = toStr(data.jobNumber);
  const totalPrice    = toStr(data.totalPrice)       || 'TBD';

  const children: (Paragraph | Table)[] = [];

  // ── APT Logo (replaces a text title) ──────────────────────────────────────────
  // The logo IS the proposal masthead. Preserve aspect ratio (1048×477 ≈ 2.2:1).
  if (logo) {
    children.push(new Paragraph({
      children: [new ImageRun({ data: logo.buf, transformation: { width: 240, height: 109 }, type: logo.type })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 },
    }));
  }
  children.push(new Paragraph({
    children: [],
    spacing: { after: 120 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: NAVY } },
  }));
  children.push(blank());

  // ── Proposal header block (plain left-aligned paragraphs) ────────────────────
  // Order: date · bold GC name · Attn · Re · address · job number
  children.push(new Paragraph({ children: [new TextRun({ text: date, size: MD, font: FONT })], spacing: { after: 40 } }));
  children.push(new Paragraph({ children: [new TextRun({ text: gcName, bold: true, size: MD, font: FONT })], spacing: { after: 40 } }));
  if (gcContact) children.push(new Paragraph({ children: [new TextRun({ text: `Attn: ${gcContact}`, size: MD, font: FONT })], spacing: { after: 40 } }));
  children.push(new Paragraph({ children: [new TextRun({ text: `Re: ${projectName}`, size: MD, font: FONT })], spacing: { after: 40 } }));
  if (projectAddr) children.push(new Paragraph({ children: [new TextRun({ text: projectAddr, size: MD, font: FONT })], spacing: { after: 40 } }));
  if (jobNumber)   children.push(new Paragraph({ children: [new TextRun({ text: `Job #: ${jobNumber}`, size: MD, font: FONT })], spacing: { after: 40 } }));
  children.push(blank());

  // ── Opening statement (no section header band) ───────────────────────────────
  children.push(bodyPara(aptOpening(projectName)));
  children.push(blank());

  // ── Scope of Work ────────────────────────────────────────────────────────────
  children.push(navyHeader('SCOPE OF WORK'));
  const sow = data.scopeOfWork ?? {};
  const std6 = sow.standard6Bullets ?? [];
  if (std6.length) {
    std6.forEach(b => children.push(bulletItem(toStr(b))));
    children.push(blank());
  }
  const sowSections: [string, unknown[] | undefined][] = [
    ['A.  SERVICE & DISTRIBUTION',                   sow.A_ServiceDistribution],
    ['B.  BRANCH POWER',                             sow.B_BranchPower],
    ['C.  LIGHTING & CONTROLS',                      sow.C_LightingControls],
    ['D.  SITE LIGHTING, UNDERGROUND & ALLOWANCES',  sow.D_SiteLightingUnderground],
    ['E.  LOW VOLTAGE INFRASTRUCTURE',               sow.E_LowVoltage],
    ['F.  PROJECT COORDINATION & CLOSEOUT',          sow.F_Coordination],
  ];
  for (const [label, bullets] of sowSections) {
    if (!bullets?.length) continue;
    children.push(subHeader(label));
    bullets.forEach(b => children.push(bulletItem(toStr(b))));
  }
  children.push(blank());

  // ── Exclusions ──────────────────────────────────────────────────────────────
  const excl = data.exclusions ?? [];
  if (excl.length) {
    children.push(navyHeader('EXCLUSIONS'));
    excl.forEach(e => children.push(bulletItem(toStr(e))));
    children.push(blank());
  }

  // ── Allowances table ─────────────────────────────────────────────────────────
  const allows = (Array.isArray(data.allowances) ? data.allowances : []).filter(a => a?.item);
  if (allows.length) {
    children.push(navyHeader('ALLOWANCES'));
    children.push(new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ tableHeader: true, children: [
          hdrCell('Item', 45), hdrCell('Qty', 15), hdrCell('Unit', 15), hdrCell('Notes', 25),
        ]}),
        ...allows.map((a, i) => new TableRow({ children: [
          dataCell(toStr(a.item), i % 2 === 0, 45),
          dataCell(String(a.footage || ''), i % 2 === 0, 15),
          dataCell(toStr(a.unit) || 'LF', i % 2 === 0, 15),
          dataCell(toStr(a.notes), i % 2 === 0, 25),
        ]})),
      ],
    }));
    children.push(blank());
  }

  // ── Takeoff table ─────────────────────────────────────────────────────────────
  const tkf = (Array.isArray(data.takeoff) ? data.takeoff : []).filter(t => t?.item);
  if (tkf.length) {
    children.push(navyHeader('MATERIAL & LABOR TAKEOFF'));
    children.push(new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ tableHeader: true, children: [
          hdrCell('Category', 18), hdrCell('Item', 20), hdrCell('Description', 32),
          hdrCell('Unit', 10), hdrCell('Qty', 8), hdrCell('Notes', 12),
        ]}),
        ...tkf.map((t, i) => new TableRow({ children: [
          dataCell(toStr(t.category), i % 2 === 0, 18, 16),
          dataCell(toStr(t.item), i % 2 === 0, 20, 16),
          dataCell(toStr(t.description), i % 2 === 0, 32, 16),
          dataCell(toStr(t.unit), i % 2 === 0, 10, 16),
          dataCell(String(t.qty ?? ''), i % 2 === 0, 8, 16),
          dataCell(toStr(t.sourceNotes).slice(0, 80), i % 2 === 0, 12, 16),
        ]})),
      ],
    }));
    children.push(blank());
  }

  // ── Terms & Conditions ───────────────────────────────────────────────────────
  const terms = data.terms ?? [];
  if (terms.length) {
    children.push(navyHeader('TERMS & CONDITIONS'));
    terms.forEach(t => children.push(numberedItem(toStr(t))));
    children.push(blank());
  }

  // ── Price summary ────────────────────────────────────────────────────────────
  children.push(navyHeader('PROPOSAL PRICE'));
  children.push(new Paragraph({
    children: [
      new TextRun({ text: 'Total Proposed Contract Value:  ', bold: true, size: MD, color: NAVY, font: FONT }),
      new TextRun({ text: totalPrice, bold: true, size: XL, color: NAVY, font: FONT }),
    ],
    alignment: AlignmentType.CENTER,
    spacing: { before: 120, after: 80 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: 'This price includes all labor, materials, permits, and coordination as described above.', size: SM, font: FONT, italics: true })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
  }));
  children.push(blank());

  // ── Signature block ────────────────────────────────────────────────────────
  children.push(navyHeader('ACCEPTANCE & SIGNATURE'));
  children.push(bodyPara('By signing below, the undersigned authorizes Accurate Power & Technology to proceed with the work described herein per the stated terms and price.'));
  children.push(blank());

  children.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: NO_BORDER,
    rows: [new TableRow({
      children: [
        new TableCell({
          width: { size: 48, type: WidthType.PERCENTAGE },
          borders: CELL_NO_BORDER,
          children: [
            new Paragraph({ children: [new TextRun({ text: 'AUTHORIZED BY (APT):', bold: true, size: SM, color: NAVY, font: FONT })], spacing: { after: 80 } }),
            ...(sig
              ? [new Paragraph({ children: [new ImageRun({ data: sig.buf, transformation: { width: 160, height: 60 }, type: sig.type })], spacing: { after: 40 } })]
              : [new Paragraph({ children: [new TextRun('')], spacing: { before: 300, after: 0 } })]
            ),
            new Paragraph({ children: [new TextRun({ text: 'Jake Salverda, Commercial A.E.', size: SM, font: FONT })], spacing: { after: 20 } }),
            new Paragraph({ children: [new TextRun({ text: `Date: ${date}`, size: SM, font: FONT })], spacing: { after: 20 } }),
          ],
        }),
        new TableCell({
          width: { size: 4, type: WidthType.PERCENTAGE },
          borders: CELL_NO_BORDER,
          children: [new Paragraph({ children: [] })],
        }),
        new TableCell({
          width: { size: 48, type: WidthType.PERCENTAGE },
          borders: CELL_NO_BORDER,
          children: [
            new Paragraph({ children: [new TextRun({ text: 'ACCEPTED BY (OWNER/GC):', bold: true, size: SM, color: NAVY, font: FONT })], spacing: { after: 80 } }),
            new Paragraph({ children: [new TextRun('')], spacing: { before: 300, after: 0 } }),
            new Paragraph({ children: [new TextRun({ text: 'Signature: _______________________________', size: SM, font: FONT })], spacing: { after: 20 } }),
            new Paragraph({ children: [new TextRun({ text: 'Print Name: _____________________________', size: SM, font: FONT })], spacing: { after: 20 } }),
            new Paragraph({ children: [new TextRun({ text: 'Date: ___________________________________', size: SM, font: FONT })], spacing: { after: 20 } }),
          ],
        }),
      ],
    })],
  }));

  // ── Build document ────────────────────────────────────────────────────────────
  const doc = new Document({
    numbering: {
      config: [
        {
          reference: 'numbered-list',
          levels: [{
            level: 0,
            format: NumberFormat.DECIMAL,
            text: '%1.',
            alignment: AlignmentType.LEFT,
            style: {
              paragraph: {
                indent: { left: convertInchesToTwip(0.5), hanging: convertInchesToTwip(0.25) },
              },
            },
          }],
        },
        {
          reference: 'bullet-list',
          levels: [{
            level: 0,
            format: NumberFormat.BULLET,
            text: '•',
            alignment: AlignmentType.LEFT,
            style: {
              paragraph: {
                indent: { left: convertInchesToTwip(0.5), hanging: convertInchesToTwip(0.25) },
              },
            },
          }],
        },
      ],
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top:    convertInchesToTwip(1.0),
            bottom: convertInchesToTwip(1.0),
            left:   convertInchesToTwip(1.0),
            right:  convertInchesToTwip(1.0),
          },
        },
      },
      children,
    }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
